name: "Conan install, package install & CMake Setup"
description: "Install conan, conan packages and sets up CMake to use the conan toolchain"
inputs:
  build-config:
    description: "build configuration either Release or Debug"
    required: true
    default: "Release"
  build-folder:
    default: build
runs:
  using: "composite"
  steps:
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Cache Conan packages
      uses: actions/cache@v4
      with:
        path: ~/.conan2
        key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile*') }}-build_type-${{ inputs.build-config }}
        restore-keys: |
          ${{ runner.os }}-conan-${{ hashFiles('**/conanfile*') }}-
          ${{ runner.os }}-conan-

    - name: Install Conan packages
      shell: bash
      run: |
        conan profile detect
        conan install . --profile=conanprofile --settings=build_type=${{ inputs.build-config }} --output-folder=${{ inputs.build-folder }} --build=missing
