name: Latest Version Check

on:
  workflow_call:
    outputs:
      version:
        description: "the version string to give to the DLL"
        value: ${{jobs.get-version.outputs.version}}

jobs:
  get-version:
    runs-on: windows-latest
    outputs:
      version: ${{steps.version_handler.outputs.version}}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run version handler
        id: version_handler
        env:
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}
        run: |
          python .github/workflows/version_handler.py
